language: python
sudo: required
dist: xenial

# install dependencies
install:
  - pip install --upgrade setuptools pip
  - |
    if [[ ! -z "$KUBE_PY" ]]; then
      # install pinned kubernetes
      pip install -e ".[test]" "kubernetes==$KUBE_PY.*"
    else
      # add --pre so that we test with prereleases of dependencies
      # to catch compatibility issues before they enter final releases
      pip install --upgrade --pre -e ".[test]"
    fi
  - source ci/minikube.env
  - ./ci/install-kube.sh
  - pip freeze

# command to run tests
script:
  - pytest --cov kubespawner -v
after_success:
  - pip install codecov
  - codecov

matrix:
  include:
    # Test the oldest supported python on
    # the latest supported kubernetes-client,
    # and use the latest supported kubernetes
    # version along for the kubernetes-client.
    - python: 3.8
      env: KUBE_PY=7 KUBE_VERSION=1.11.10
    - python: 3.7
      env: KUBE_PY=8 KUBE_VERSION=1.12.10
    - python: 3.6
      env: KUBE_PY=9 KUBE_VERSION=1.13.10
    - python: 3.5
      env: KUBE_PY=10 KUBE_VERSION=1.14.0
    # We test nightly python and kubernetes versions
    # that are beyond what the kubernetes-client/python
    # library supports currently.
    - python: nightly
      env: KUBE_PY=11 KUBE_VERSION=1.15.0
    - python: 3.8
      env: &unsupported_kubernetes KUBE_PY=10 KUBE_VERSION=1.16.*
  allow_failures:
    - python: nightly
    - env: *unsupported_kubernetes
  fast_finish: true
